// TaskForm's styles, built per render from the theme.

import { StyleSheet } from 'react-native';
import type { Colors } from '@/ui/theme';

export const makeTaskFormStyles = (c: Colors) =>
  StyleSheet.create({
    label: { fontSize: 13, fontWeight: '600', color: c.muted, marginBottom: 8, marginTop: 4 },
    counter: { fontSize: 11, color: c.faint, textAlign: 'right', marginTop: -8, marginBottom: 12 },
    input: {
      backgroundColor: c.inputBg,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 15,
      color: c.text,
      borderWidth: 1,
      borderColor: c.border,
      marginBottom: 12,
    },
    row: { flexDirection: 'row', gap: 8, marginBottom: 12, alignItems: 'center' },
    titleRow: { flexDirection: 'row', gap: 8, alignItems: 'flex-start' },
    titleInput: { flex: 1 },
    // Fields just filled by voice — same border weight, accent tint.
    voiceFilled: { borderColor: c.primary, backgroundColor: c.primarySoft },
    voiceLive: { fontSize: 13, fontStyle: 'italic', color: c.primary, marginTop: -4, marginBottom: 12 },
    voiceError: { fontSize: 12, color: c.danger, marginTop: -4, marginBottom: 12 },
    voiceNote: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginTop: -4,
      marginBottom: 12,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 10,
      backgroundColor: c.track,
    },
    voiceHeard: { fontSize: 12, color: c.muted },
    voiceUndo: { fontSize: 13, fontWeight: '700', color: c.primary },
    chip: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 10,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.inputBg,
    },
    chipText: { fontSize: 14, fontWeight: '600', color: c.muted },
    chipTextSelected: { color: c.onAccent },
    chipShareSelected: { backgroundColor: c.primary, borderColor: c.primary },
    dateBtn: {
      flex: 1,
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.inputBg,
    },
    dateBtnText: { fontSize: 15, color: c.text },
    hint: { fontSize: 12, color: c.faint, marginTop: -6, marginBottom: 10 },
    // A real input problem (end time not after the start).
    hintError: { fontSize: 12, color: c.danger, marginTop: -6, marginBottom: 10 },
    // The collapsed recurrence button (accent-colored when recurring).
    repeatBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.inputBg,
      marginBottom: 12,
    },
    repeatBtnText: { fontSize: 15, fontWeight: '700', color: c.muted },
    // Two fields side by side (icon | tags, time | end, reminders | repeat).
    pairRow: { flexDirection: 'row', gap: 12, alignItems: 'flex-start' },
    pairCol: { flex: 1, minWidth: 0 },
    iconBtn: {
      width: 46,
      height: 40,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.5,
      marginBottom: 12,
    },
    iconBtnEmpty: { borderStyle: 'dashed', borderColor: c.border, backgroundColor: c.inputBg },
    iconBtnOn: { borderColor: c.primary, backgroundColor: c.primarySoft },
    clearIcon: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: c.track,
    },
    // The repeat summary in a half-width column: may wrap to two lines rather than cut.
    repeatBtnTextShrink: { flex: 1, marginLeft: 8, fontSize: 14, lineHeight: 18 },
    iconGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 12 },
    iconCell: {
      width: 42,
      height: 42,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: c.inputBg,
      borderWidth: 1,
      borderColor: c.border,
    },
    iconCellSel: { borderWidth: 2, borderColor: c.primary, backgroundColor: c.primarySoft },
    repeatBtnTextOn: { color: c.primary },
    dayChipSel: { borderColor: c.primary, backgroundColor: c.primary },
    // Quick date shortcuts under the date button (Today / Tomorrow / Next week).
    quickRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 8 },
    quickChip: {
      minHeight: 40,
      paddingHorizontal: 14,
      borderRadius: 20,
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.inputBg,
    },
    dayChipText: { fontSize: 13, fontWeight: '700', color: c.muted },
    dayChipTextSel: { color: c.onAccent },
    actions: { flexDirection: 'row', gap: 12, marginTop: 20 },
    saveBtn: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 15,
      borderRadius: 14,
      backgroundColor: c.primary,
      shadowColor: c.primary,
      shadowOpacity: 0.35,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
      elevation: 4,
    },
    saveBtnText: { fontSize: 15, fontWeight: '700', color: c.onAccent },

    // — Draft subtask editor (creation) —
    subRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 7, gap: 10 },
    subBullet: { width: 6, height: 6, borderRadius: 3, backgroundColor: c.faint },
    subTitle: { flex: 1, fontSize: 14, color: c.text },
    subDelete: { fontSize: 20, color: c.faint, paddingHorizontal: 4 },
    subAddRow: { flexDirection: 'row', gap: 8, marginBottom: 4, alignItems: 'center' },
    subInput: {
      flex: 1,
      backgroundColor: c.inputBg,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 15,
      color: c.text,
      borderWidth: 1,
      borderColor: c.border,
    },
    subAddBtn: {
      width: 44,
      alignSelf: 'stretch',
      borderRadius: 12,
      backgroundColor: c.primarySoft,
      alignItems: 'center',
      justifyContent: 'center',
    },
    subAddText: { fontSize: 20, color: c.primary, fontWeight: '600' },
  });
