// TaskForm's styles, built per render from the theme.

import { StyleSheet } from 'react-native';
import type { Colors } from '@/ui/theme';

export const makeTaskFormStyles = (c: Colors) =>
  StyleSheet.create({
    label: { fontSize: 13, fontWeight: '600', color: c.muted, marginBottom: 8, marginTop: 4 },
    counter: { fontSize: 11, color: c.faint, textAlign: 'right', marginTop: -8, marginBottom: 12 },
    input: {
      backgroundColor: c.inputBg,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 15,
      color: c.text,
      borderWidth: 1,
      borderColor: c.border,
      marginBottom: 12,
    },
    row: { flexDirection: 'row', gap: 8, marginBottom: 12, alignItems: 'center' },
    titleRow: { flexDirection: 'row', gap: 8, alignItems: 'flex-start' },
    titleInput: { flex: 1 },
    // Fields just filled by voice — same border weight, accent tint.
    voiceFilled: { borderColor: c.primary, backgroundColor: c.primarySoft },
    voiceLive: { fontSize: 13, fontStyle: 'italic', color: c.primary, marginTop: -4, marginBottom: 12 },
    voiceError: { fontSize: 12, color: c.danger, marginTop: -4, marginBottom: 12 },
    voiceNote: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginTop: -4,
      marginBottom: 12,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 10,
      backgroundColor: c.track,
    },
    voiceHeard: { fontSize: 12, color: c.muted },
    voiceUndo: { fontSize: 13, fontWeight: '700', color: c.primary },
    chip: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 10,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.inputBg,
    },
    chipText: { fontSize: 14, fontWeight: '600', color: c.muted },
    chipTextSelected: { color: c.onAccent },
    chipShareSelected: { backgroundColor: c.primary, borderColor: c.primary },
    dateBtn: {
      flex: 1,
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.inputBg,
    },
    dateBtnText: { fontSize: 15, color: c.text },
    clearBtn: { paddingVertical: 12, paddingHorizontal: 14 },
    clearBtnText: { fontSize: 14, color: c.muted, fontWeight: '600' },
    hint: { fontSize: 12, color: c.faint, marginTop: -6, marginBottom: 10 },
    // A real input problem (end time not after the start).
    hintError: { fontSize: 12, color: c.danger, marginTop: -6, marginBottom: 10 },
    // The collapsed recurrence button (accent-colored when recurring).
    repeatBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.inputBg,
      marginBottom: 12,
    },
    repeatBtnText: { fontSize: 15, fontWeight: '700', color: c.muted },
    repeatBtnTextOn: { color: c.primary },
    repeatRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 12 },
    freqBtn: {
      flexGrow: 1,
      flexBasis: '30%',
      alignItems: 'center',
      paddingVertical: 10,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.inputBg,
    },
    // "Every how many days? / Day of the month" row.
    freqNumRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 12 },
    freqNumLabel: { fontSize: 14, fontWeight: '600', color: c.text },
    freqNumInput: {
      width: 64,
      textAlign: 'center',
      backgroundColor: c.inputBg,
      borderRadius: 10,
      paddingVertical: 8,
      fontSize: 15,
      fontWeight: '700',
      color: c.text,
      borderWidth: 1,
      borderColor: c.border,
    },
    freqNumHint: { flex: 1, fontSize: 12, color: c.faint },
    // "Feb 12 ×" chips for selected yearly dates.
    yearDateChip: { width: undefined, paddingHorizontal: 10, backgroundColor: c.primarySoft, borderColor: c.primary },
    yearDateChipText: { fontSize: 13, fontWeight: '700', color: c.primary },
    freqBtnSel: { borderColor: c.primary, backgroundColor: c.primarySoft, borderWidth: 2 },
    freqBtnText: { fontSize: 14, fontWeight: '600', color: c.muted },
    freqBtnTextSel: { color: c.primary },
    dayRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 12 },
    dayChip: {
      width: 42,
      paddingVertical: 8,
      borderRadius: 10,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.inputBg,
    },
    dayChipSel: { borderColor: c.primary, backgroundColor: c.primary },
    // Quick date shortcuts under the date button (Today / Tomorrow / Next week).
    quickRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 8 },
    quickChip: {
      minHeight: 40,
      paddingHorizontal: 14,
      borderRadius: 20,
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.inputBg,
    },
    dayChipText: { fontSize: 13, fontWeight: '700', color: c.muted },
    dayChipTextSel: { color: c.onAccent },
    actions: { flexDirection: 'row', gap: 12, marginTop: 20 },
    saveBtn: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 15,
      borderRadius: 14,
      backgroundColor: c.primary,
      shadowColor: c.primary,
      shadowOpacity: 0.35,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
      elevation: 4,
    },
    saveBtnText: { fontSize: 15, fontWeight: '700', color: c.onAccent },

    // — Draft subtask editor (creation) —
    subRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 7, gap: 10 },
    subBullet: { width: 6, height: 6, borderRadius: 3, backgroundColor: c.faint },
    subTitle: { flex: 1, fontSize: 14, color: c.text },
    subDelete: { fontSize: 20, color: c.faint, paddingHorizontal: 4 },
    subAddRow: { flexDirection: 'row', gap: 8, marginBottom: 4, alignItems: 'center' },
    subInput: {
      flex: 1,
      backgroundColor: c.inputBg,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 15,
      color: c.text,
      borderWidth: 1,
      borderColor: c.border,
    },
    subAddBtn: {
      width: 44,
      alignSelf: 'stretch',
      borderRadius: 12,
      backgroundColor: c.primarySoft,
      alignItems: 'center',
      justifyContent: 'center',
    },
    subAddText: { fontSize: 20, color: c.primary, fontWeight: '600' },
  });
