// Style factory for the setup wizard (PATTERN: no module-level StyleSheet.create,
// the factory runs at render time so it follows theme changes — the look step
// changes the theme while the wizard is open).

import { StyleSheet } from 'react-native';
import type { Colors } from '@/ui/theme';

export const makeWizardStyles = (c: Colors) =>
  StyleSheet.create({
    screen: { flex: 1 },
    topBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingTop: 52,
      paddingHorizontal: 24,
      paddingBottom: 8,
      minHeight: 96,
    },
    progressWrap: { flex: 1, marginRight: 16 },
    progressLabel: { fontSize: 12, fontWeight: '700', color: c.muted, marginBottom: 6 },
    progressTrack: { height: 6, borderRadius: 3, backgroundColor: c.track, overflow: 'hidden' },
    progressFill: { height: 6, borderRadius: 3, backgroundColor: c.primary },
    skipAll: { fontSize: 14, fontWeight: '600', color: c.muted, paddingVertical: 6 },

    scroll: { flex: 1 },
    content: { paddingHorizontal: 24, paddingTop: 12, paddingBottom: 24 },
    center: { alignItems: 'center' },
    badge: {
      width: 96,
      height: 96,
      borderRadius: 48,
      backgroundColor: c.primarySoft,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 20,
      alignSelf: 'center',
    },
    emoji: { fontSize: 44 },
    title: { fontSize: 26, fontWeight: '800', color: c.text, textAlign: 'center' },
    body: { fontSize: 15, lineHeight: 22, color: c.muted, textAlign: 'center', marginTop: 10, marginBottom: 20 },
    note: { fontSize: 12, lineHeight: 18, color: c.faint, textAlign: 'center', marginTop: 12 },

    label: { fontSize: 13, fontWeight: '600', color: c.muted, marginBottom: 8, marginTop: 14 },
    chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    chip: {
      paddingVertical: 9,
      paddingHorizontal: 14,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.inputBg,
    },
    chipOn: { backgroundColor: c.primary, borderColor: c.primary },
    chipText: { fontSize: 14, fontWeight: '600', color: c.text },
    chipTextOn: { color: c.onAccent },
    seg: { flexDirection: 'row', gap: 8 },
    segBtn: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 11,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.inputBg,
    },
    segBtnOn: { backgroundColor: c.primary, borderColor: c.primary },
    segText: { fontSize: 14, fontWeight: '700', color: c.muted },
    segTextOn: { color: c.onAccent },
    accentRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 14 },
    accentItem: { alignItems: 'center', width: 64 },
    accentSwatch: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: 'transparent',
    },
    accentSwatchOn: { borderColor: c.text },
    accentCheck: { color: '#fff', fontSize: 16, fontWeight: '800' },
    accentLabel: { fontSize: 11, color: c.muted, marginTop: 4, textAlign: 'center' },

    inputRow: { flexDirection: 'row', gap: 8, alignItems: 'flex-start' },
    input: {
      flex: 1,
      backgroundColor: c.inputBg,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 16,
      color: c.text,
      borderWidth: 1,
      borderColor: c.border,
    },
    inputHalf: { flex: 1 },
    twoCols: { flexDirection: 'row', gap: 10 },
    preview: {
      marginTop: 10,
      padding: 12,
      borderRadius: 10,
      backgroundColor: c.primarySoft,
    },
    previewText: { fontSize: 13, color: c.text },
    live: { fontSize: 13, fontStyle: 'italic', color: c.primary, marginTop: 8 },
    error: { fontSize: 13, color: c.danger, marginTop: 8 },

    primaryBtn: {
      marginTop: 18,
      minHeight: 50,
      borderRadius: 14,
      backgroundColor: c.primary,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 16,
    },
    primaryBtnOff: { opacity: 0.4 },
    primaryText: { fontSize: 16, fontWeight: '700', color: c.onAccent },
    outlineBtn: {
      marginTop: 12,
      minHeight: 48,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: c.primary,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 16,
    },
    outlineText: { fontSize: 15, fontWeight: '700', color: c.primary },
    googleBtn: {
      marginTop: 18,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
      minHeight: 52,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.card,
    },
    googleMark: { fontSize: 20, fontWeight: '800', color: c.primary },
    googleText: { fontSize: 16, fontWeight: '700', color: c.text },

    success: {
      marginTop: 12,
      padding: 14,
      borderRadius: 12,
      backgroundColor: c.primarySoft,
      alignItems: 'center',
    },
    successText: { fontSize: 15, fontWeight: '700', color: c.text, textAlign: 'center' },
    okText: { fontSize: 15, fontWeight: '700', color: c.done, textAlign: 'center', marginTop: 14 },
    warnText: { fontSize: 13, color: c.muted, textAlign: 'center', marginTop: 12, lineHeight: 19 },

    switchRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 14 },
    switchLabel: { fontSize: 15, color: c.text, flex: 1, marginRight: 12 },

    stepRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, marginTop: 14 },
    stepNum: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: c.primarySoft,
      alignItems: 'center',
      justifyContent: 'center',
    },
    stepNumText: { fontSize: 14, fontWeight: '800', color: c.primary },
    stepText: { flex: 1, fontSize: 15, lineHeight: 22, color: c.text, paddingTop: 3 },

    summaryRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, marginTop: 10 },
    summaryCheck: { fontSize: 16, color: c.done, fontWeight: '800' },
    summaryText: { flex: 1, fontSize: 15, color: c.text, lineHeight: 22 },

    footer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingHorizontal: 24,
      paddingTop: 12,
      paddingBottom: 36,
      borderTopWidth: 1,
      borderTopColor: c.border,
      backgroundColor: c.bg,
    },
    backBtn: { minHeight: 48, minWidth: 64, justifyContent: 'center' },
    backText: { fontSize: 15, fontWeight: '700', color: c.muted },
    skipStep: { minHeight: 48, justifyContent: 'center', paddingHorizontal: 4 },
    skipStepText: { fontSize: 14, fontWeight: '600', color: c.muted },
    nextBtn: {
      flex: 1,
      minHeight: 50,
      borderRadius: 14,
      backgroundColor: c.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    nextText: { fontSize: 16, fontWeight: '700', color: c.onAccent },
  });
