// Core data types for the app.
// Each table has a corresponding type defined here.
// Shared sync fields: updated_at (last write wins), deleted_at (soft delete).

export type Priority = 'low' | 'medium' | 'high';
// 'numeric': progress bar (current/target). 'milestone': same logic as
// task/subtask — can be split into steps (goal_milestones), completed
// manually or automatically. Both types can now have a deadline (previously
// only a separate 'deadline' type had one — see migration011).
export type GoalType = 'numeric' | 'milestone';
// Habit tracking type. 'binary' = did it / didn't; 'numeric' = amount target;
// 'timer' = countdown (target_amount is the target in seconds, amount is
// accumulated seconds).
export type HabitKind = 'binary' | 'numeric' | 'timer';

// Recurrence rule. Used by both tasks and habits (a JSON TEXT column — new
// fields don't require a migration). Types:
//   daily    → every day
//   weekly   → specific days of the week when weekdays is set;
//              when weekdays is empty and timesPerWeek>0, it's a FLEXIBLE
//              QUOTA ("X times a week", any day is fine — see
//              helpers.isQuotaSchedule)
//   monthly  → a specific day of the month
//   interval → every X days (anchor is the reference day, which is scheduled)
//   yearly   → specific dates every year
export interface Recurrence {
  freq: 'daily' | 'weekly' | 'monthly' | 'interval' | 'yearly';
  // for weekly: [1,3,5] = Mon, Wed, Fri (0=Sunday ... 6=Saturday)
  weekdays?: number[];
  // for weekly FLEXIBLE QUOTA: how many times a week (meaningful when weekdays is empty)
  timesPerWeek?: number;
  // for monthly: day of the month (1-31)
  monthDay?: number;
  // for interval: every how many days (>=1)
  every?: number;
  // for interval: reference day "YYYY-MM-DD" — this day and every `every` days after it are scheduled
  anchor?: string;
  // for yearly: ["MM-DD", ...] (no year component)
  dates?: string[];
}

// Sync fields shared by all records.
export interface SyncFields {
  id: string;            // UUID, generated by the device
  updated_at: string;    // ISO 8601, used for conflict resolution
  deleted_at: string | null; // non-null means deleted
  synced: 0 | 1;         // 1 = pushed to the cloud, 0 = pending
}

export interface User extends SyncFields {
  email: string | null;
  is_anonymous: 0 | 1;
}

export interface Task extends SyncFields {
  user_id: string;
  title: string;
  due_date: string | null;       // ISO 8601; if a time is embedded, it's the start/due time
  end_time: string | null;       // "HH:MM"; end time on the same day, null = none
  priority: Priority;
  recurrence: Recurrence | null; // null = one-off
  remind_at: string | null;      // "09:00"; remind at this time ON the due date (null = no reminder). Independent of due_date's time.
  completed_at: string | null;   // null = not completed
}

export interface Goal extends SyncFields {
  user_id: string;
  title: string;
  goal_type: GoalType;
  target_value: number | null;   // for numeric: the target (e.g. 100 km)
  current_value: number;         // for numeric: current value (e.g. 40 km)
  unit: string | null;           // "km", "books", "hours"
  deadline: string | null;       // "YYYY-MM-DD"; now usable with both types
  // Written manually/automatically (once all steps are completed) only for
  // 'milestone' goals. Always NULL for 'numeric' goals — completion is
  // derived from current_value>=target_value (see goalRepo.isCompleted).
  completed_at: string | null;
  remind_at: string | null;      // e.g. "08:30", daily entry reminder time
  start_date: string | null;     // "YYYY-MM-DD"; day zero for pace/projection calculations (see goalProjection.ts). Can be NULL for older goals.
  // The part of current_value NOT REPRESENTED by entries (see migration019):
  // the value accumulated before that change, plus the user manually
  // editing "Current value". Readers don't use this — current_value is
  // already kept as baseline + sum of entries (goalRepo.recomputeFromEntries).
  value_baseline: number;
}

// A step/part of a goal. Used in two ways:
//   in a 'milestone' goal → a simple checklist item (subtask pattern):
//     checked manually, amount is always NULL.
//   in a 'numeric' goal with amount set → an INTERMEDIATE THRESHOLD: the
//     step's percentage is derived CUMULATIVELY from the goal's
//     current_value (steps fill in position order), NOT checked manually;
//     the completed column is unused in this mode.
//     (see goalMilestoneRepo.milestoneViews)
// due_date is an optional step due date in both modes.
export interface GoalMilestone extends SyncFields {
  goal_id: string;
  title: string;
  completed: 0 | 1;
  position: number; // creation order; the list is shown in this order
  amount: number | null;   // meaningful only for numeric goals: the intermediate threshold amount
  due_date: string | null; // "YYYY-MM-DD" optional step due date
}

// A record added via a free-form amount entry ("Add") on a goal's 'Overview'
// tab. It's purely a LOG (audit log) — goal.current_value is already the
// single source of truth and is NOT DERIVED from this table; it just keeps
// a "what was added when" history so the user can see it in the Overview
// tab. updated_at is both the creation and (if any) deletion timestamp —
// same pattern as every other table in SyncFields.
export interface GoalEntry extends SyncFields {
  goal_id: string;
  amount: number; // can be positive or negative (a correction)
}

// How contribution to a linked goal works: 'per_completion' (+1 per
// completed day, the only meaningful option for binary) | 'amount' (that
// day's amount × goal_factor is added to the goal, meaningful only for
// numeric/timer). NULL = 'per_completion' (the backward-compatible default).
export type GoalContribution = 'per_completion' | 'amount';

export interface Habit extends SyncFields {
  user_id: string;
  goal_id: string | null;        // can be linked to a goal later
  title: string;
  kind: HabitKind;               // 'binary' | 'numeric' | 'timer'
  remind_at: string | null;      // e.g. "08:30", daily reminder time
  icon: string | null;           // emoji (visual identity), null = none
  color: string | null;          // hex color "#rrggbb", null = default
  schedule: Recurrence | null;   // which days apply; null = every day
  target_amount: number | null;  // numeric: daily amount (e.g. 8) · timer: target seconds · binary: null
  unit: string | null;           // "glasses", "pages"; meaningful for numeric (timer/binary: null)
  start_date: string | null;     // "YYYY-MM-DD"; null = since the beginning
  end_date: string | null;       // "YYYY-MM-DD"; null = indefinite
  goal_contribution: GoalContribution | null; // see GoalContribution; NULL = per_completion
  goal_factor: number;           // multiplier, only used in 'amount' mode; default 1
}

// A task's subtask (a simple checklist item).
// Deliberately minimal: no date/priority of its own, just a title + status.
export interface Subtask extends SyncFields {
  task_id: string;
  title: string;
  completed: 0 | 1;
  position: number; // creation order; the list is shown in this order
}

// Multiple reminders. A habit/task/goal's remind_at field (a single "HH:MM")
// is no longer used — each entity can now have ZERO OR MORE reminder times
// via this table (see reminderRepo, notifications.scheduleHabitReminders,
// etc.). The old remind_at columns are backfilled into this table in
// migration016 but left untouched in the DB (no data loss, just no longer read).
export type ReminderEntityType = 'habit' | 'task' | 'goal';

export interface Reminder extends SyncFields {
  entity_type: ReminderEntityType;
  entity_id: string;
  time: string; // "HH:MM"
}

// A record is created each time a habit is checked off for a day.
// Streaks and stats are computed from these records.
export interface HabitLog {
  id: string;
  habit_id: string;
  log_date: string;     // in "2026-06-28" format, date only
  completed: 0 | 1;     // for numeric habits: 1 once amount >= target
  amount: number;       // amount done that day (unused for binary habits, 0)
  updated_at: string;
}
